resurrectionamericancar/cars/urls.py
from django.urls import path
from . import views

app_name= 'cars'

urlpatterns = [
    path('', views.cars_list,name="list"), 
    # path('<slug:slug>', views.post_page,name="page"), 
    path('new-car/', views.car_new,name="new-car"), 
    path('<int:id>', views.car_page,name="car-page"), 
]

resurrectionamericancar/resurrectionamericancar/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root': settings.MEDIA_ROOT}),
	re_path(r'^static/(?P<path>.*)$',serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('home/', views.home),
    path('', views.home),
    path('about', views.about),
    path('cars/', include('cars.urls')),
    path('users/', include('users.urls')),
   
]

#urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

resurrectionamericancar/users/urls.py
from django.urls import path
from . import views


app_name= 'users'

urlpatterns = [
    path('register/', views.register_view,name="register"), 
    path('login/', views.login_view,name="login"), 
    path('logout/', views.logout_view,name="logout"), 
   
]

resurrectionamericancar/templates/about.html
{% extends "layout.html" %} 
{% block title %}
    About 
{% endblock %} 
{% block content%}
<h1 class="text-center">Resurrection American Car</h1>

<div class="about-content">
    <p>
        En <strong>Resurrection American Car</strong>, nos enorgullece ofrecer una experiencia única para nuestros clientes. 
        Estamos comprometidos con la satisfacción total de quienes confían en nosotros, ya sea que estén adquiriendo un vehículo de calidad, accesorios o servicios especializados. 
        Nos aseguramos de que cada uno de nuestros clientes reciba atención personalizada, profesional y amable.
    </p>

    <p>
        Nuestra misión es proporcionar vehículos de las mejores marcas y modelos, asegurando su total funcionalidad y seguridad. Ya sea que compre en línea o en nuestra tienda física, siempre encontrará opciones que se ajusten a sus necesidades y presupuesto.
    </p>

    <p>
        <strong>Dirección:</strong> Calle 46 entre 35 y 37, Miami, FL. ¡Lo esperamos con gusto para ofrecerle el mejor servicio y la más amplia variedad de autos!
    </p>

    <p>
        Nuestro equipo está siempre dispuesto a ayudarle con cualquier consulta o necesidad. En <strong>Resurrection American Car</strong>, su satisfacción es nuestra prioridad.
    </p>
</div>

{% endblock %}

resurrectionamericancar/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock %}

{% block content %}
<div class="container-fluid p-0">
    <!-- Fila de la imagen de fondo -->
    <div class="row vh-100 justify-content-center align-items-start" style="background-image: url('/static/cars/icons/cardealerbig.jpg'); background-size: cover; background-position: center;">
        <!-- Capa de superposición para el texto -->
        <div class="col-12 text-center text-white mt-5 px-3" style="background-color: rgba(0, 0, 0, 0.5);">
            <h2 class="display-4 font-weight-bold text-shadow">WELCOME TO</h2>
            <h1 class="display-1 font-weight-bold text-shadow">Resurrection American Car</h1>
        </div>
    </div>
</div>
{% endblock %}

resurrectionamericancar/templates/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <title>{% block title %} Res. American Car {% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">    
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav me-auto">
        <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'cars:list' %}">Cars</a></li>
        {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link new-car" href="{% url 'cars:new-car' %}"><i class="fas fa-car"></i> New Car</a></li>        
        {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Register</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Login</a></li>
        {% endif %}
      </ul>
      <ul class="navbar-nav ms-auto"> <!-- Alineación a la derecha -->
        {% if user.is_authenticated %}
          <li class="nav-item">
            <form action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="nav-link btn btn-logout">Logout</button>
            </form>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<main class="container my-4">
     {% block content %}
     {% endblock %}
</main>
</body>
</html>